### ISSUE TITLE
Unable to write to file

### ISSUE THREAD

**Issue by GAsplund** [4321ba/noteblock_music_yoinker#1]
Whenever you record, it tries to write to a file, but I guess it refers to the file name incorrectly on at least Windows systems.
Stacktrace:
```
[m[32m[18:57:34] [Sound engine/INFO] [ab.no.NoteblockMusicYoinker/]: Recording harp at time 0 with pitch 1.5 and volume 0.98.
[m[1;31m[18:57:34] [Sound engine/ERROR] [ab.no.NoteblockMusicYoinker/]: error writing to file recorded_music/2020-11-09T18:57:19.877.csv
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: java.io.FileNotFoundException: recorded_music\2020-11-09T18:57:19.877.csv (The filename, directory name, or volume label syntax is incorrect)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at java.io.FileOutputStream.open0(Native Method)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at java.io.FileOutputStream.open(Unknown Source)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at java.io.FileWriter.<init>(Unknown Source)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at ab.noteblock_music_yoinker.NoteblockMusicYoinker.onSoundPlayed(NoteblockMusicYoinker.java:75)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraftforge.eventbus.ASMEventHandler_12_NoteblockMusicYoinker_onSoundPlayed_PlaySoundSourceEvent.invoke(.dynamic)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraft.client.audio.SoundEngine.lambda$null$5(SoundEngine.java:318)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraft.client.audio.ChannelManager$Entry.func_217890_b(SourceFile:27)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:173)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:151)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at net.minecraft.client.audio.SoundEngineExecutor.func_213178_c(SourceFile:42)
[m[32m[18:57:34] [Sound engine/INFO] [STDERR/]: [ab.noteblock_music_yoinker.NoteblockMusicYoinker:onSoundPlayed:80]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by GAsplund** [comment]
I came to a solution to the issue by changing the filename. When it ran it tried to use illegal characters (colons) for the file name. I solved it by changing the way the LocalDateTime formats into a string.
```java
file_to_write = "recorded_music/" + java.time.LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss")) + ".csv";
```
After I changed the code to the above it worked perfectly on my machine.

**Comment by 4321ba** [comment]
Thank you for trying it! You are right, not every system likes colons as filenames, I'll change it in the source code, thanks for the fix!

**Comment by 4321ba** [comment]
Btw, this format also looks much nicer!

**Comment by 4321ba** [comment]
I also needed to add `java.time.format.` before the `DateTimeFormatter` to get it to compile, but the new 1.1 release jar has this fix now.
